stages:
  - build

variables:
  IMAGE_NAME: git.uwaterloo.ca:5050/mw2auyeu/team102-4/backend
  IMAGE_TAG: $IMAGE_NAME:latest

instrumented tests:
  stage: test
  script:

    # install packages needed by emulator
    - apt-get install libx11-dev libpulse0 libgl1 libnss3 libxcomposite-dev libxcursor1 libasound2 --yes

    # install android sdk components and emulator
    - sdkmanager --sdk_root=${ANDROID_SDK_ROOT} "platform-tools" "emulator" "system-images;android-${EMULATOR_IMAGE};default;armeabi-v7a"

    # download script for emulator waiting
    - wget --quiet --output-document=android-wait-for-emulator https://raw.githubusercontent.com/travis-ci/travis-cookbooks/0f497eb71291b52a703143c5cd63a217c8766dc9/community-cookbooks/android-sdk/files/default/android-wait-for-emulator
    - chmod +x android-wait-for-emulator

    # create virtual device named "test"
    - echo no | avdmanager -v create avd -n test -k "system-images;android-${EMULATOR_IMAGE};default;armeabi-v7a"

    # start adb server
    - adb start-server

    # run emulator and tests
    - emulator -avd test -no-boot-anim -no-window -no-audio -no-snapshot &
    - ./android-wait-for-emulator
    - adb shell input keyevent 82
    - ./gradlew connectedDebugAndroidTest
#
#build_backend_docker_image:
#  stage: build
#  image: docker:cli
#  services:
#    - docker:dind
#  variables:
#    DOCKER_BUILDKIT: 1
#    DOCKER_CLI_EXPERIMENTAL: enabled
#  before_script:
#    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
#    - docker buildx create --use
#    # Create the firebase admin key file
#    - echo "$FIREBASE_ADMIN_KEY_BASE64" | base64 -d > backend/src/main/resources/firebase-admin-key.json
#  script:
#    - docker buildx build --platform linux/amd64,linux/arm64 -t $IMAGE_TAG --push .
#
#  # Only run this job when changes are made to the backend directory
#  rules:
#    - if: '$CI_COMMIT_BRANCH == "main"'
#      exists:
#        - Dockerfile
#        - .dockerignore
#      changes:
#        - backend/**/*