stages:
  - build

variables:
  IMAGE_NAME: git.uwaterloo.ca:5050/mw2auyeu/team102-4/backend
  IMAGE_NAME_GEOCODER: git.uwaterloo.ca:5050/mw2auyeu/team102-4/geocoder
  IMAGE_TAG: $IMAGE_NAME:latest
  IMAGE_TAG_GEOCODER: $IMAGE_NAME_GEOCODER:latest

build_backend_and_geocoder_docker_image:
  stage: build
  image: docker:cli
  services:
    - docker:dind

  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    # Create the firebase admin key file
    - echo "$FIREBASE_ADMIN_KEY_BASE64" | base64 -d > backend/src/main/resources/firebase-admin-key.json
  script:
    - docker build -t $IMAGE_TAG backend
    - docker push $IMAGE_TAG
    - docker build -t $IMAGE_TAG_GEOCODER geocoder
    - docker push $IMAGE_TAG_GEOCODER
  # Only run this job when changes are made to the backend directory
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      exists:
        - Dockerfile
        - .dockerignore
      changes:
        - backend/**/*