stages:
  - build

variables:
  IMAGE_NAME: git.uwaterloo.ca:5050/mw2auyeu/team102-4/backend
  IMAGE_TAG: $IMAGE_NAME:latest

build_backend_docker_image:
  stage: build
  image: docker:cli
  services:
    - docker:dind
  variables:
    DOCKER_BUILDKIT: 1
    DOCKER_CLI_EXPERIMENTAL: enabled
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker buildx create --use
    # Create the firebase admin key file
    - echo "$FIREBASE_ADMIN_KEY_BASE64" | base64 -d > backend/src/main/resources/firebase-admin-key.json
  script:
    - docker buildx build --platform linux/amd64,linux/arm64 -t $IMAGE_TAG --push .

  # Only run this job when changes are made to the backend directory
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      exists:
        - Dockerfile
        - .dockerignore
      changes:
        - backend/**/*